#define INIT_X 1
#define END_X 75
#define HEIGHT 12
#define LENGTH 75
#define SPACE 32
#define P_DAMAGE 10
#define LIFE 100
#define BASE_ENEMY_LIFE 20
#define HARD_ENEMY_LIFE 50
#define PLAT_INIT 50
#define BON_ENEM_INIT 3
#define ENEM_x_POS 50
#define BONU_x_POS 30 
#define PLAT_X_POS 40 
#define Y_JUMP 5
#define ESC 27
